### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by jasnell** [nodejs/quic#1]
This repo is dedicated to working on a QUIC implementation for Node.js core. I am still getting the fundamentals pulled together so won't be landing any PRs yet, but wanted to at least get things bootstrapped.

I will be creating a quic team. Please comment here if you'd like to be included on that.

There are several prerequisites that need to be looked at before we can really get moving:

1. Integrating ngtcp2 for all supported Node.js platforms
2. Our version of OpenSSL needs modifications to support QUIC. We would need to float those changes as it's not clear if they can be merged upstream. It's also not yet clear if those changes would affect non-QUIC OpenSSL uses. Will be investigating. QUIC requires TLS 1.3.
3. The existing UDPWrap needs to be modified to allow it to more easily be used directly from the native side, including writing and reading data.

Please add any additional thoughts you may have to this thread.

**Comment by KromDaniel** [comment]
Hey, I'd like to volunteer to join the team :)

**Comment by jasnell** [comment]
@KromDaniel ... you should have an invite to join the team!

**Comment by mcollina** [comment]
I’m in!

**Comment by caijw** [comment]
great

**Comment by danbev** [comment]
I'd like to join the team.

**Comment by yosuke-furukawa** [comment]
I would like to join this team!!!

**Comment by aitchkhan** [comment]
I'd love to be a part of this team.

**Comment by veera83372** [comment]
How can I be part of this team?
