### ISSUE TITLE
TODO: Update patched openssl & fixup

### ISSUE THREAD

**Issue by jasnell** [nodejs/quic#103]
Within the past week or so, ngtcp2 updated to use a new version of the patched openssl library with a whole new set of APIs based on Boring (details here: https://github.com/openssl/openssl/pull/8797).

These represent what will ultimately be the official openssl APIs so we need to switch. Unfortunately, the implementation appears to be based on Openssl 3 so it's going to need to be backported with floated patches until we can upgrade to a version of OpenSSL that has these built in (the PR that adds them hasn't even landed yet so .....)

The good news is once we land this, ngtcp2 provides utility APIs that greatly reduce what we need to implement and maintain within Node.js (over half of the code in node_quic_crypto.h goes away and handshake/crypto logic becomes *much* easier.)

I'm investigating what we need to do to port the changes.

**Comment by jasnell** [comment]
@tmshort ... In Node.js, we currently use a vendored in version of OpenSSL 1.1.1b. Do you happen to know off the top of your head if your port of the BoringSSL QUIC APIs has any chance of working on 1.1.1b? I'm working through the patches now and there are some definite bits missing in 1.1.1b that I'll have to investigate.

**Comment by tmshort** [comment]
It has a zero chance of making openssl 1.1.1b, since that's already been released (current version = 1.1.1c). 1.1.1d is likely to be released sometime around 9/11/2019 (when 1.1.0 is EOL). The PR is not ready to be committed, based on the comments on the PR. There's a copyright issue that needs to be resolved by the OMC, which is why there's a HOLD label on it. And, the OpenSSL committers are focusing on FIPS for 3.0.0, and many non-FIPS PRs are not getting looked at.

**Comment by jasnell** [comment]
No no, sorry that's not what I meant. In order to get the new apis to be usable in the node.js implementation at all at this point, I would have to backport and float a patch over our vendored in version of 1.1.1b. But I think that definitely answers my question... I think for now I'm going to stick with @tatsuhiro-t's original patch strategy and just temporarily re-implement his ngtcp2_crypto.h methods on top of that so that the boringssl apis aren't required. Once a version of openssl 3 is released that has these APIs and we can safely upgrade the statically linked openssl in node.js to use it, we'll just move over then

**Comment by jasnell** [comment]
Thank you for the quick response! :-) ... excellent work on the API ports btw, it's definitely appreciated.

**Comment by tmshort** [comment]
Sorry, mis-interpreted your question. I suspect that it may be reasonably easy to port to 1.1.1. The significant master branch (3.0.0) changes for FIPS are at a much lower, crypto layer.

**Comment by jasnell** [comment]
I'll definitely see if a backport is possible, but while the copyright bit is still an issue I wouldn't be able to ship anything in node.js anyway so it may be best just to wait until that is resolved. That should give enough time for any of the open issues in the PR to be resolved also :-)

**Comment by jasnell** [comment]
Backport done but does need to be updated based on most recent changes to the original PR. Will update that next week but this issue can be closed.
