### ISSUE TITLE
[HEADS UP] Rebasing Master, Squashing QUIC commits

### ISSUE THREAD

**Issue by jasnell** [nodejs/quic#146]
Heads up @nodejs/quic (@danbev and @addaleax in particular)... I'm going to be rebasing nodejs/quic master and squashing a large number of the quic specific commits down in order to make further rebasing easier. As it stands now, we're a couple hundred commits ahead which makes rebasing quite a bit more difficult. I'll squash first, then rebase.

**Comment by jasnell** [comment]
Ok, squash and reorganization of the commits is done. Rebasing next.

**Comment by jasnell** [comment]
Ok, done!

**Comment by addaleax** [comment]
Since the main commit after the rebase no longer contains Author information, here’s what I’ve gathered from the git log:

```
Author: Anna Henningsen <anna@addaleax.net>
Author: Daniel Bevenius <daniel.bevenius@gmail.com>
Author: gengjiawen <technicalcute@gmail.com>
Author: James M Snell <jasnell@gmail.com>
Author: Lucas Pardue <lucaspardue.24.7@gmail.com>
Author: oyyd <oyydoibh@gmail.com>
```

I would suggest including them in a `Co-authored-by:` field.

**Comment by jasnell** [comment]
Nice, that was on my todo list for this morning and you just saved me a bit
of time :-D woo!

**Comment by jasnell** [comment]
Co-authored-by fields added!
