### ISSUE TITLE
Ideas for showing current state of Node.js QUIC implementation at SeattleJS (Oct 10th)

### ISSUE THREAD

**Issue by trivikr** [nodejs/quic#148]
Hi team,

I'm going to give a talk about status of current implementation of QUIC in Node.js at Seattle on Oct 10th ([details](https://github.com/seattlejs/seattlejs/issues/174)) and would like your suggestions on what to include.

This is a practice run for the conference talk scheduled for [CascadiaJS](https://2019.cascadiajs.com/) next month.

Here's what I've currently planned:
* Give a 10 minute summary from [HTTP/3 Explained](https://http3-explained.haxx.se/en/) from @bagder
* If I can find time for preparation, I might make client-server responses entertaining by showing analogy of two people talking and how their dialogue will change in HTTP 1/2/3
* Show live metrics on stage comparing HTTP 1/2/3
  * Need to think of a single application which can do this
* Show difference between connection establishment latency between Node's HTTP/2 and QUIC modules
* Can I simulate TCP head-of-line blocking problem live on stage?
* Simulate connection migration live on stage - in h2 a new TCP connection will be created while in QUIC the same connection ID will continue to be used?

I want to end my talk by live coding a unit test for QUIC and create a PR - any suggestions? This was successful at NodeConfEU 2019
As Hacktoberfest is going on, I would encourage viewers to contribute to QUIC or Node.js/Open Source in general.

Regards,
trivikram

**Comment by jasnell** [comment]
I will be continuing to try to get the fixed openssl bits done by then but master should be working as is for simple demos.

**Comment by trivikr** [comment]
The Meetup talk can be viewed on YouTube at https://www.youtube.com/watch?v=GqXC00ZBBrY
