### ISSUE TITLE
TODO: fix cctest/test_quic_verifyhostnameidentity

### ISSUE THREAD

**Issue by addaleax** [nodejs/quic#163]
I’ve disabled the test in #162 because it would block compilation and there wasn’t any obvious way to fix it, but we should get that up running again soon, if possible.

**Comment by lundibundi** [comment]
This can be closed via https://github.com/nodejs/quic/pull/169.

**Comment by danbev** [comment]
@lundibundi Thanks for pointing that out, I should have closed it but missed it. Will close now.
