### ISSUE TITLE
TODO: fix test-quic-idle-timeout

### ISSUE THREAD

**Issue by addaleax** [nodejs/quic#164]
The test was recently added in #160 but is timing out 100 % of the time for me (x64 Linux).

**Comment by jasnell** [comment]
hmm... I ran it once and it worked, now it's not. Weird.

**Comment by oyyd** [comment]
After pulling the master today, it doesn't work for me too. Need to find out the reason.

**Comment by addaleax** [comment]
Fixed in #166
