### ISSUE TITLE
Add qlog support

### ISSUE THREAD

**Issue by rmarx** [nodejs/quic#185]
**Is your feature request related to a problem? Please describe.**
It is generally difficult to debug or gain insight into QUIC and HTTP/3 purely from text-based, unstructured logs. Complex issues with long running connections or during the particulars of connection setup are hard to track down and reason about. More insight aids developers first, later students and researchers. 

**Describe the solution you'd like**
For some time, we have been working on "qlog", a standardized structured logging format for QUIC (see https://github.com/quiclog/internet-drafts). It is basically a well-defined JSON file with specified event names and associated data. This format is now supported by over half of the current QUIC implementations and was just today added to ngtcp2 (https://github.com/ngtcp2/ngtcp2/commit/22d9c6d278aa02b49da01305190114834175c9ef). Outputting this standard format allows you to easily use tools like "qvis" (https://qvis.edm.uhasselt.be) for visualization. More tools will follow in the future. 

It would be great if NodeJS's QUIC integration also supports qlog. Initially, it could be just to allow setting the necessary ngtcp2 parameters (see commit above) so qlog files with internal state are written. Eventually, I would hope NodeJS could add additional events from the top-level application into the qlog files as well.

**Comment by jasnell** [comment]
This has definitely been on my todo list to dig into. Once we're a bit further along we'll have to explore how best to support this. It will most likely be similar to how we currently support TLS keylogging... that is, we will generate events on the javascript side with the necessary information and it will be the responsibility of user code to push that out to files. That will give the user the tools they need to enable it but will keep them in complete control over the actual logging.
