### ISSUE TITLE
Heads up: Rebase

### ISSUE THREAD

**Issue by addaleax** [nodejs/quic#225]
I’ll rebase this repository’s master branch against nodejs/master shortly… pinging people who currently have open PRs:

@danbev @juanarbol @jasnell @oyyd you’ll need to rebase your PRs against the new quic/master branch afterwards, sorry

**Comment by addaleax** [comment]
The old HEAD was at b3b9c0e438654f0cef504c46598ccc10af15c1f8, the new one is at 3bd75b5f9a34547296e386a2875819fe4aecc9ca

**Comment by jasnell** [comment]
Thank you @addaleax !
