### ISSUE TITLE
HEADS UP: Refactoring commit history

### ISSUE THREAD

**Issue by jasnell** [nodejs/quic#226]
@nodejs/quic ... all, I'm going to be refactoring the commit history soon to clean it up in preparation for opening the WIP PR against nodejs/node master. This will likely happen either later in the day Thursday or Friday. The current quic/master will be moved into a branch and I will squash down into as few commits as possible. Once that is done, all open PRs will need to be rebased. I'll update here when it is completed.

**Comment by addaleax** [comment]
@jasnell During the rebase I’ve moved 3 commits that we should be able to keep as-is to *before* “quic: initial protocol implementation”. Afaict, the rest could basically be squashed together into a single huge commit :see_no_evil:

**Comment by jasnell** [comment]
All.. working on this now... expect a bit of churn in master today

**Comment by jasnell** [comment]
Done!
