### ISSUE TITLE
QuicBuffer

### ISSUE THREAD

**Issue by jasnell** [nodejs/quic#23]
Ok, so the implementation is in a state where things are basically working but there is still a ton of work to do in order to get it complete. There's one major PR that I'll get landed later on today. The next big piece will be nailing down the implementation of `QuicBuffer` so the data flow from JS to C++ and back, with as little memcpy'ing as possible, works and is as efficient as possible. I have a few other things to work on over the next couple of days but I'll be working sporadically on the `QuicBuffer` implementation over the coming days and would love input on it.

The basic break down is this:

`QuicSocket` wraps the `uv_udp_t` handle and deals with sending packets. Unlike traditional UDP, QUIC includes error handling that requires packets to be re-transmitted until they are acknowledged by the peer. This means we cannot simply fire and forget a `uv_buf_t` and free it when the libuv callback is triggered. We have to keep the `ub_buf_t` around until ngtcp2 receives and processes the acknowledgement.

Data is sent at multiple places: 1) by QuicSocket itselr (e.g. version negotiation, close, errors, etc) ... 2) by QuicSession (and the QuicServerSession and QuicClientSession specializations) during TLS handshake and regular stream management, and 3) by QuicStream.

There are multiple data buffers at play. TLS handshake has it's own outgoing buffer, every QuicStream has it's own outgoing buffer. There are several places in the code where more transient buffers are used. It's fairly complicated but the bottom-line is that we cannot free buffers as soon as the libuv callback is triggered because we may need to retransmit those multiple times.

The current `QuicBuffer` implementation is modeled after the example code in ngtcp2, and it works reasonably well for what it does right now but it does not really do what we need it to do, particularly with regards to proper Stream API support callbacks when we can actually free data. It also depends heavily on memcpy at several places making it quite inefficient. It needs a better implementation.

It will likely be a few days before I can really dig in but I would love to open this bit up to others who may have some good ideas on how to handle the data flow here (ahem, @addaleax :-D .. since I love what you did with http2's internal data flow).

If someone wanted to start poking around with those bits, I'm happy to answer questions or help point in the right direction :-)

**Comment by addaleax** [comment]
@jasnell I just reviewed #18, but I guess that was a bit late? I can try to go through the source here once and clean up some stuff in the next one or two days, if you want?

**Comment by jasnell** [comment]
Heh, yeah I just went ahead and landed it. It's going to need a good going over anyway. I'm about to open the iteration-4 branch and PR in just a minute that has a start on a new QuicBuffer implementation. That would be the great place to start I think.
