### ISSUE TITLE
QuicClientSession.on('keylog') doesn't work before it's connected

### ISSUE THREAD

**Issue by oyyd** [nodejs/quic#249]
The code below won't emit `keylog` event:

```js
const client = createSocket();

clientSession.on('keylog', (...args) => {
  // this won't get called
});

clientSession.connect({})
```

putting the `clientSession.on('keylog')` inside the callback of `connect()` works: 

```js
const client = createSocket();

clientSession.connect({}, () => {
  clientSession.on('keylog', (...args) => {
    // this won't get called
  });
});
```

From the code here: https://github.com/nodejs/quic/blob/277b68463228676013145080bf81032accff425b/lib/internal/quic/util.js#L584 

`self[kHandle]` is `undefined` before `QuicClientSession` gets connected so that this event won't be emitted from the C++ side.

**Comment by oyyd** [comment]
Just find that it's referenced in #246.

**Comment by jasnell** [comment]
Yep, I'll be opening a PR soon that fixes this
