### ISSUE TITLE
Openssl & TLS 1.3

### ISSUE THREAD

**Issue by jasnell** [nodejs/quic#3]
OpenSSL 1.1.1 has landed, and with it the TLS 1.3 support we need... however, there are two patches we need to bring in to make this work correctly:

* https://github.com/tatsuhiro-t/openssl/commit/920a331423f69f14b4871e35b476ea4fd573993a
* https://github.com/tatsuhiro-t/openssl/commit/33efa52ca15c4798f3df5b4d96dba7b72368b54a

Just leaving this here as a heads up. I'll be bringing these in next week but need to do some other testing to make sure they don't break anything else in core.

**Comment by tatsuhiro-t** [comment]
I first wrote the patch for openssl 1.1.1, and then migrated to master.
If I remember correctly, not much changes I have to made.

**Comment by jasnell** [comment]
I just stepped through it and applied the changes to 1.1.1. Everything is looking good so far. Really appreciate the work you've done to pave the way here @tatsuhiro-t

**Comment by jasnell** [comment]
Landed!
