### ISSUE TITLE
Heads Up: Rebasing from nodejs/node master

### ISSUE THREAD

**Issue by jasnell** [nodejs/quic#384]
Just a heads up that I will be working on rebasing again from nodejs/master. This is always fairly disruptive as quite a few things have changed. Expect a few force pushes to master.

**Comment by splitice** [comment]
Perhaps tag / branch this branch beforehand so that anyone debugging issues against this build has a clear reference point?

Of course there are other options (e.g forks), but this seems clearest.

**Comment by jasnell** [comment]
Branch already done :-) https://github.com/nodejs/quic/tree/pre-squash8-20200507

**Comment by jasnell** [comment]
Rebase, squash, and force push on master is completed!
