### ISSUE TITLE
Implement Build Configure Switch

### ISSUE THREAD

**Issue by jasnell** [nodejs/quic#55]
Implement temporary configure build switch to optionally enable building QUIC support.

Windows:
```
vcbuild enable-experimental-quic
```

POSIX:
```
./configure --enable-experimental-quic
```

**Comment by trivikr** [comment]
Updated `enable-experimental-quic` to `experimental-quic` in issue description as per https://github.com/nodejs/quic/pull/83#issuecomment-524105691
