### ISSUE TITLE
TODO: Ensure server preferred address is working correctly

### ISSUE THREAD

**Issue by jasnell** [nodejs/quic#63]
When the client receives a server preferred address, it needs to be validated and optionally used by the client. The basic mechanism for this is in place but needs to be fully verified and tested.

**Comment by oyyd** [comment]
The example of ngtcp2 manages multiple endpoints for preferred address: https://github.com/ngtcp2/ngtcp2/blob/cb1a26150926d265c3d1cc57950418b108fd1836/examples/server.cc#L2165. Maybe we need to manage another `uv_udp_handle` in `QuicSocket` for supporting preferred address too?

**Comment by jasnell** [comment]
We can definitely look at it but I'm not certain how much benefit there. Tho, it would be intriguing to be able to bind a single server at the JavaScript side to multiple addresses so worth exploring

**Comment by jasnell** [comment]
@addaleax @danbev @nodejs/quic ... would love to get opinions on this one..

The short version is this: In theory, it ought to be possible to associate a single `QuicSession` instance with multiple local UDP endpoints. These, for instance, may be on different ports or associated with different network adapters. Obviously, however, with the current code, we bind to only a single `QuicSocket` and UDP endpoint. This simplifies things significantly but reduces the utility of things like the preferred address capability.

Here is the description for preferred address from the spec:

```
QUIC allows servers to accept connections on one IP address and
attempt to transfer these connections to a more preferred address
shortly after the handshake.  This is particularly useful when
clients initially connect to an address shared by multiple servers
but would prefer to use a unicast address to ensure connection
stability.  This section describes the protocol for migrating a
connection to a preferred server address.
```

The question then becomes, how do we want to best support this capability, both from an internal implementation and public facing API point of view. Fundamentally, it changes the association of `QuicSocket` to `QuicSession` from One-to-Many to Many-to-Many.

**Comment by addaleax** [comment]
Without having looked into it a ton, does the choice of the UDP endpoint affect the QUIC protocol state in any way? 

> Fundamentally, it changes the association of `QuicSocket` to `QuicSession` from One-to-Many to Many-to-Many.

@jasnell Would it work if we keep the `QuicSocket`:`QuicSession` relationship 1:n, and instead change the `QuicSocket`:`UDPWrap` relationship from 1:1 to 1:n? (This kind of hinges on the answer to the question above)

I think that would require us storing a `QuicSocket` → `UDPWrap` relationship for knowing which endpoint to use for sending packets, but not introduce much more complexity than that?

**Comment by danbev** [comment]
@jasnell I've not been following along very well but intend to dedicate Friday to catching up and will take a  closer look at this then.

**Comment by jasnell** [comment]
> Without having looked into it a ton, does the choice of the UDP endpoint affect the QUIC protocol state in any way?

Somewhat, and it varies between Client and Server.

Currently, a server is only permitted to change it's UDP endpoint as it relates to the preferred address. For instance, the server is permitted to accept requests on one UDP endpoint then migrate that to it's preferred address only once. During the migration, however, the server would end up receiving/sending data potentially on *both*.

A client is permitted to migrate to a new UDP endpoint at anytime but there is a critical path validation process that must be performed.

Protocol state is impact only as a result of the path validation outcome.

This whole mechanism is quite complex and there's an entire section of the QUIC spec dedicated to it. I would recommend starting there... https://tools.ietf.org/html/draft-ietf-quic-transport-24#section-9

**Comment by jasnell** [comment]
Thinking about it further, I think making the `QuicSocket` to `UDPWrap` relationship 1:n may be the way to go here. I'm imagining an API similar to:

```js
// Create the QuicSocket with a single local Endpoint
const socket = createSocket({ port: 1234, address: 'localhost' })

// Add a new local endpoint to the socket. The endpoint won't
// be immediately bound. It will follow the same implicit binding
// logic as the original endpoint.
socket.addEndpoint({ port: 1235, address: 'localhost' })

// Then, tell the socket to listen. This has the effect of binding
// both endpoints and setting both to accept connections. Called 
// this way, the `localhost:1234` address is configured as the
// preferred address given that it was the first added.
socket.listen();

// Adding an endpoint after listening works just fine. It will bind
// immediately, however.
socket.addEndpoint({ port: 1236, address: 'localhost' })

// To change the preferred address for *new* server QuicSession
// instances, the socket.addEndpoint() would allow for a preferred
// option...
socket.addEndpoint({ port: 1237, address: 'localhost', preferred: true })

// To make the API symmetrical, it ought to be possible to enumerate and
// remove endpoints that have been added to a QuicSocket...
const endpoints = socket.getEndpoints();

// If there are open QuicSession instances that are actively using the
// given endpoint, then removing it should fail with an error. The
// endpoint can only be removed if it's not being used actively.
socket.removeEndpoint(endpoints[1]);

// When a QuicSocket is closed, all associated endpoints would be closed.
socket.close();
```

There are obviously a number of details here that would need to be figured out around state management but there really should be no impact on the rest of the QUIC implementation outside of `QuicSocket` (JS and C++ layer)

**Comment by jasnell** [comment]
I've got an implementation plan forming for this. I'll be getting started working on it. It's going to add just a bit of complexity to the C++ QuicSocket but not a lot, and will change the way we get the local address for the QuicSocket, but that's also fairly trivial and ngtcp2 is already set up to handle it. Majority of the complexity will be at the JS level... fortunately, however, it's going to allow us to simplify the actual public API of `QuicSocket`. Users will manipulate the `UDPSocket`/`UDPWrap` instances directly if they want to set properties on it. Overall implementation should be fairly straightforward.

**Comment by jasnell** [comment]
Preferred address is working fine with https://github.com/nodejs/quic/pull/256
