### ISSUE TITLE
Design Approach

### ISSUE THREAD

**Issue by jasnell** [nodejs/quic#7]
Just wanted to drop some implementation notes into this since there are some others looking at pitching in. Will be updating this as we go.

The UDP and TLS mechanisms need to happen entirely at the native layer. The implementation here is *not* building on the existing `dgram` or `tls` modules that exist in core. The UDP socket, TLS context, and interaction with the ngtcp2 APIs will happen entirely at the native layer.

More to come...

**Comment by jasnell** [comment]
@nodejs/quic ... Ok, question for the team: A single UDP socket can be used as both a server endpoint and a client... the question is: should we allow for that?

In other words: If I create a QUIC Server and QUIC Client within the same Node.js application, would each of those always have their own *separate* `uv_udp_t` bound to their own local ports, or should we allow for them to *share* a single `uv_udp_t` bound to a single local port?

The answer will have a fairly significant impact on the underlying implementation so I'd like to get it figured out now.

**Comment by mcollina** [comment]
I’m +1 on having a shared API, I think it would spark more creativity, expecially on the P2P world.

**Comment by jasnell** [comment]
Agreed... ok, reworking around a shared API...
