### ISSUE TITLE
TODO: Implement the HTTP/3 layer

### ISSUE THREAD

**Issue by jasnell** [nodejs/quic#77]
The HTTP/3 layer will involve use of nghttp3 and an additional set of specializations for the native QuicSession/QuicClientSession/QuicServerSession/QuicStream classes. Work on this will begin in early September.

**Comment by jasnell** [comment]
Depends on https://github.com/nodejs/quic/pull/83 landing first

**Comment by Justsnoopy30** [comment]
(Early September passed a month ago)

**Comment by jasnell** [comment]
Indeed it did and work has started.

**Comment by Justsnoopy30** [comment]
Ok. Is it usable at this point yet?

**Comment by Justsnoopy30** [comment]
By usable, I mean I can run a nodejs http/3 website that serves a page, and Chrome Canary with experimental http/3 support enabled can access the website and see the page.

**Comment by jasnell** [comment]
Not yet. The underlying ngtcp2 library changed a number of the APIs relating to the tls handshake that assume the use of the BoringSSL QUIC apis that have not yet landed in OpenSSL 3. Given that we're using OpenSSL 1.1.1 and need to port those APIs, it's taking a bit longer to get completed.

**Comment by Justsnoopy30** [comment]
Ok.

**Comment by trivikr** [comment]
My experiments with running QUIC in Node.js, and loading website from Chrome will be documented at https://github.com/trivikr/node-http-servers#quic-server

**Comment by jasnell** [comment]
Basic http3 implementation is in. Not completed 100% but operational.
